Replaced the non-const getter of IHeaders for an operator[]
zombre98/dems-zia-api pull request #6
Opened 2019-02-14 13:17 UTC by Nyquase

2019-02-14 15:33 UTC, zombre98 requested changes

2019-02-14 15:33 UTC, zombre98 commented on Heading.hpp
> +	virtual std::string &operator[](const std::string &headerName) = 0;
You need to update the ReadMe.md

2019-02-14 15:35 UTC, Nyquase commented on Heading.hpp
> +	virtual std::string &operator[](const std::string &headerName) = 0;
oups

2019-02-14 15:38 UTC, Nyquase commented on Heading.hpp
> +	virtual std::string &operator[](const std::string &headerName) = 0;
Done

2019-02-15 09:59 UTC, zombre98 approved these changes

2019-02-15 09:59 UTC, merged